CREATE TABLE IF NOT EXISTS "bf_v10"."role_requests" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text NOT NULL,
  "requested_role" text NOT NULL,
  "reason" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "requested_at" timestamp with time zone DEFAULT now() NOT NULL,
  "reviewed_by" text,
  "reviewed_at" timestamp with time zone,
  "review_note" text,
  CONSTRAINT "role_requests_user_id_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "bf_v10"."user"("id") ON DELETE cascade,
  CONSTRAINT "role_requests_reviewed_by_user_id_fk"
    FOREIGN KEY ("reviewed_by") REFERENCES "bf_v10"."user"("id")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "role_requests_user_status_idx"
  ON "bf_v10"."role_requests" ("user_id", "status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "role_requests_status_idx"
  ON "bf_v10"."role_requests" ("status");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "role_requests_one_pending_per_user_idx"
  ON "bf_v10"."role_requests" ("user_id")
  WHERE "status" = 'pending';
