CREATE TABLE IF NOT EXISTS "bf_v10"."role_audit_logs" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "actor_user_id" text,
  "target_user_id" text NOT NULL,
  "action" text NOT NULL,
  "old_roles" text[] NOT NULL,
  "new_roles" text[] NOT NULL,
  "source" text NOT NULL,
  "role_request_id" integer,
  "note" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "role_audit_logs_actor_user_id_user_id_fk"
    FOREIGN KEY ("actor_user_id") REFERENCES "bf_v10"."user"("id"),
  CONSTRAINT "role_audit_logs_target_user_id_user_id_fk"
    FOREIGN KEY ("target_user_id") REFERENCES "bf_v10"."user"("id") ON DELETE cascade,
  CONSTRAINT "role_audit_logs_role_request_id_role_requests_id_fk"
    FOREIGN KEY ("role_request_id") REFERENCES "bf_v10"."role_requests"("id")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "role_audit_logs_created_at_idx"
  ON "bf_v10"."role_audit_logs" ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "role_audit_logs_actor_idx"
  ON "bf_v10"."role_audit_logs" ("actor_user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "role_audit_logs_target_idx"
  ON "bf_v10"."role_audit_logs" ("target_user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "role_audit_logs_action_idx"
  ON "bf_v10"."role_audit_logs" ("action");
